const test=require('node:test');const assert=require('node:assert/strict');
const {converter,vetor,cardinal,circular,chuva,normalizeWindyPointForecast:normalize,criarCliente}=require('../src/sources/windy');
const {integrarWindy}=require('../src/logic/windyMerge');
const now=new Date('2026-09-22T12:00:00Z'),start=Date.parse('2026-09-22T03:00:00Z');
function fixture(){return {ts:Array.from({length:9},(_,i)=>start+i*10800000),units:{'temp-surface':'K','rh-surface':'%','wind_u-surface':'m*s-1','wind_v-surface':'m*s-1','gust-surface':'m*s-1','past3hprecip-surface':'mm','lclouds-surface':'%','waves_height-surface':'m','waves_period-surface':'s','waves_direction-surface':'deg','swell1_height-surface':'m','pm2p5-surface':'µg*m-3'},'temp-surface':Array(9).fill(300),'rh-surface':Array(9).fill(70),'wind_u-surface':Array(9).fill(3),'wind_v-surface':Array(9).fill(4),'gust-surface':Array(9).fill(10),'past3hprecip-surface':Array(9).fill(2),'lclouds-surface':Array(9).fill(80),'waves_height-surface':Array(9).fill(2),'waves_period-surface':Array(9).fill(8),'waves_direction-surface':[359,1,359,1,359,1,359,1,359],'swell1_height-surface':Array(9).fill(1),'pm2p5-surface':Array(9).fill(10)};}
test('units, missing values and meteorological vector',()=>{assert.equal(converter(300,'K','temperature'),26.850000000000023);assert.equal(converter(10,'m*s-1','speed'),36);assert.equal(converter(null,'K','temperature'),null);assert.equal(converter(20,'unknown','temperature'),null);assert.equal(converter(NaN,'K','temperature'),null);assert.equal(vetor(3,4).velocidadeKmh,5);assert.equal(cardinal(vetor(0,-5).direcaoGraus),'N');assert.equal(cardinal(circular([359,1])),'N');assert.equal(circular([0,180]),null);assert.equal(vetor(0,0).direcaoGraus,null);});
test('timestamp alignment, full rain windows, no UV/probability inference',()=>{const r=normalize(fixture(),'weather','gfs',now);assert.equal(r.tempMax,26.9);assert.equal(r.umidadeMin,70);assert.equal(r.rajadaMaxKmh,36);assert.equal(r.precipitacaoTotalMm,16);assert.equal(r.periodos.manha.precipitacaoMm,4);assert.equal(r.atual.condicao,'Nublado');assert.equal(r.atual.horario,now.toISOString());assert.equal(r.uvMax,undefined);assert.equal(r.periodos.manha.probabilidadeChuva,undefined);});
test('missing parameters, unequal arrays, invalid timestamps never shift indexes',()=>{const j=fixture();j['temp-surface']=[null,290];j.ts[0]='invalid';delete j['rh-surface'];delete j.units['gust-surface'];const r=normalize(j,'weather','gfs',now);assert.equal(r.tempMin,16.9);assert.equal(r.umidadeMin,null);assert.equal(r.rajadaMaxKmh,null);assert.equal(r.atual,null);assert.throws(()=>normalize({ts:[]},'weather','gfs',now));});
test('overlapping rain is not double-counted and gaps are not zero',()=>{const rows=Array.from({length:7},(_,i)=>({ts:start+i*3600000,rain:3}));assert.equal(chuva(rows,start,start+21600000),6);rows[3].rain=null;assert.equal(chuva(rows,start,start+21600000),null);});
test('waves and CAMS data normalized independently',()=>{const sea=normalize(fixture(),'sea','gfsWave',now);assert.equal(sea.alturaMaxDiaM,2);assert.equal(sea.periodos[0].direcaoOnda,'N');assert.equal(sea.periodos[0].marulhoMaxM,1);const air=normalize(fixture(),'air','cams',now);assert.equal(air.pm25Medio,10);assert.equal(air.uvMax,undefined);});
test('fallback preserves probabilities, UV and field provenance',()=>{const base={tempMin:20,tempMax:30,condicaoGeral:'Sol',periodos:{manha:{probabilidadeChuva:55,precipitacaoMm:5},tarde:{},noite:{}}};const weather=normalize(fixture(),'weather','gfs',now);weather.tempMin=null;const merged=integrarWindy(base,null,{uvMax:8,pm25Medio:5},{weather,air:normalize(fixture(),'air','cams',now)},'Open-Meteo');assert.equal(merged.base.tempMin,20);assert.equal(merged.base.tempMax,26.9);assert.equal(merged.base.periodos.manha.probabilidadeChuva,55);assert.equal(merged.qualidadeAr.uvMax,8);assert.equal(merged.fontesPorCampo.tempMin,'Open-Meteo');assert.equal(merged.fontesPorCampo.tempMax,'Windy (gfs)');});
test('HTTP errors, invalid JSON, shuffled data, timeout, cache and key separation',async t=>{
 const original=process.env.WINDY_API_KEY,map=process.env.WINDY_MAP_FORECAST_API_KEY;process.env.WINDY_API_KEY='unit-test-only-point';delete process.env.WINDY_MAP_FORECAST_API_KEY;
 try{
  for(const status of [204,400,401,403,429,500]) await t.test(`HTTP ${status}`,async()=>{const client=criarCliente({fetchImpl:async()=>({ok:status<300,status}),log:()=>{}});await assert.rejects(client(-22,-43,'weather'),new RegExp(String(status)));});
  await t.test('deduplicates concurrent and cached calls',async()=>{let calls=0;const client=criarCliente({fetchImpl:async(_,o)=>{calls++;const request=JSON.parse(o.body);assert.equal(request.key,'unit-test-only-point');assert.equal(request.model,'gfs');await new Promise(r=>setTimeout(r,5));return {ok:true,status:200,json:async()=>fixture()};},log:()=>{}});await Promise.all([client(-22,-43,'weather'),client(-22,-43,'weather')]);await client(-22,-43,'weather');assert.equal(calls,1);});
  await t.test('testing data refused',async()=>{const client=criarCliente({fetchImpl:async()=>({ok:true,status:200,json:async()=>({...fixture(),warning:'randomly shuffled development data'})}),log:()=>{}});await assert.rejects(client(-22,-43,'weather'),/embaralhados/);});
  await t.test('timeout and private provider body never exposed',async()=>{for(const failure of [Object.assign(new Error('secret'),{name:'TimeoutError'}),new Error('secret')]){const client=criarCliente({fetchImpl:async()=>{throw failure;},log:()=>{}});await assert.rejects(client(-22,-43,'weather'),e=>!e.message.includes('secret'));}});
  await t.test('missing key skips network',async()=>{delete process.env.WINDY_API_KEY;assert.equal(await criarCliente({fetchImpl:()=>assert.fail('network')})(-22,-43,'weather'),null);});
 }finally{if(original===undefined)delete process.env.WINDY_API_KEY;else process.env.WINDY_API_KEY=original;if(map===undefined)delete process.env.WINDY_MAP_FORECAST_API_KEY;else process.env.WINDY_MAP_FORECAST_API_KEY=map;}
});
