const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function emitter(){const events=new Map();return {on:(k,f)=>{if(!events.has(k))events.set(k,new Set());events.get(k).add(f);},off:(k,f)=>events.get(k)?.delete(f),emit:(k,v)=>events.get(k)?.forEach(f=>f(v)),count:()=>[...events.values()].reduce((n,s)=>n+s.size,0)};}
function harness({configured=true,mobile=false,failScript=false}={}) {
 const els=new Map(),windowEvents={},urls=[],calls={init:0,picker:0,close:0,resize:0,views:[],overlays:[]};
 function element(){return {value:'',options:[],disabled:false,textContent:'',handlers:{},addEventListener(k,f){this.handlers[k]=f;},add(o){this.options.push(o);if(!this.value)this.value=o.value;},replaceChildren(){this.options=[];this.value='';},set selectedIndex(i){this.value=this.options[i]?.value;}};}
 const api={map:{...emitter(),setView:(p,z)=>calls.views.push(p),invalidateSize:()=>calls.resize++,remove:()=>{}},picker:{...emitter(),close:()=>calls.close++,open:()=>calls.picker++},store:{...emitter(),getAllowed:()=>['wind','temp'],get:()=> 'wind',set:(k,v)=>calls.overlays.push([k,v])}};
 const location={href:'http://localhost/mapas.html?cidade=a',search:'?cidade=a'};
 const config={configurado:configured,key:configured?'unit-test-map':null,mensagem:'Mapas indisponíveis: chave Map Forecast não configurada no servidor.',ativa:'a',bases:[{chave:'a',nome:'Base A',uf:'RJ',latitude:-22,longitude:-43},{chave:'b',nome:'Base B',uf:'ES',latitude:-20,longitude:-40}]};
 const context={URL,URLSearchParams,AbortSignal,Map,Set,Number,Boolean,Object,Promise,Error,Option:function(text,value){this.text=text;this.value=value;},location,history:{replaceState:(_,__,url)=>{location.href=String(url);}},matchMedia:()=>({matches:!mobile}),setTimeout,clearTimeout,document:{getElementById:id=>{if(!els.has(id))els.set(id,element());return els.get(id);},createElement:()=>element(),head:{append:el=>{urls.push(el.src);queueMicrotask(()=>failScript?el.onerror():el.onload());}}},fetch:async()=>({ok:true,json:async()=>config}),L:{marker:()=>({addTo(){return this;},bindPopup(){},remove(){}})},windyInit:(_,cb)=>{calls.init++;cb(api);},window:{addEventListener:(k,f)=>windowEvents[k]=f,removeEventListener:(k)=>delete windowEvents[k]}};
 vm.runInNewContext(fs.readFileSync('public/mapas.js','utf8'),context);
 return {els,api,calls,urls,windowEvents,location,ready:()=>new Promise(r=>setTimeout(r,20))};
}
test('map single initialization, base changes, allowed overlays, picker and cleanup',async()=>{
 const h=harness();await h.ready();assert.equal(h.calls.init,1);assert.equal(h.urls.length,2);assert.deepEqual(h.els.get('cim-map-layer').options.map(o=>o.value),['wind','temp']);
 const base=h.els.get('cim-map-base');base.value='b';base.handlers.change();assert.equal(h.calls.views.at(-1).join(','),'-20,-40');assert.match(h.location.href,/cidade=b/);assert.equal(h.calls.init,1);assert.equal(h.urls.length,2);
 const layer=h.els.get('cim-map-layer');layer.value='temp';layer.handlers.change();assert.deepEqual(h.calls.overlays.at(-1),['overlay','temp']);h.els.get('cim-map-picker').handlers.click();assert.equal(h.calls.picker,1);
 h.windowEvents.resize();assert.ok(h.calls.resize>=2);h.windowEvents.pagehide({persisted:true});assert.ok(h.api.store.count()>0);h.windowEvents.pagehide({persisted:false});assert.equal(h.api.store.count(),0);assert.equal(h.api.map.count(),0);assert.equal(h.api.picker.count(),0);
});
test('mobile does not force desktop picker',async()=>{const h=harness({mobile:true});await h.ready();assert.equal(h.els.get('cim-map-picker').disabled,true);h.api.map.emit('click',{latlng:{lat:-22,lng:-43}});assert.equal(h.calls.picker,0);h.windowEvents.pagehide({persisted:false});});
test('missing key does not fetch SDK; blocked scripts display error',async()=>{const h=harness({configured:false});await h.ready();assert.equal(h.calls.init,0);assert.equal(h.urls.length,0);assert.match(h.els.get('cim-map-status').textContent,/não configurada/);const fail=harness({failScript:true});await fail.ready();assert.equal(fail.calls.init,0);assert.match(fail.els.get('cim-map-status').textContent,/Mapa indisponível/);});
